### ISSUE TITLE
Review hub docs and update info architecture

### ISSUE THREAD

**Issue by dcwalk** [cosmos/gaia#1055]
## Summary

We've just merged in the gov docs and so the current docs structure could use some care and updating as part of #977

## Problem Definition

Currently the docs at https://hub.cosmos.network/ have some non-intuitive aspects: "resources" show up in nav twice, there are local gaia "tutorials" and sdk "tutorials" , some key resources are buried, and within each section the order of pages doesn't match the flow of content (mostly Governance). 

## Proposal

- [x] review the structure of current docs 
- [x] propose a new info. architecture and get feedback here
- [x] update docs with final structure
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by dcwalk** [comment]
I did a first pass review of the current structure here: https://hackmd.io/vM_RWIS1Rk-A3XLGT0M0pw?view
Pasting in my summary notes:
- Sitemap plugin not working, consider testing new one? https://www.npmjs.com/package/vuepress-plugin-sitemap2
- Translation not set up and following correct doc structure https://vuepress.vuejs.org/guide/i18n.html#site-level-i18n-config: 
  - need locales in config (https://github.com/cosmos/cosmos-sdk/blob/master/docs/.vuepress/config.js)
  - need per-language folder structure
- Ask for specific pattern?
  - Folder name for section 
  - Use README within folder 
  - Use frontmatter for page title + ordering? https://github.com/cosmos/vuepress-theme-cosmos#file-configuration
- READMEs kind of operate like strange placeholders, e.g.:
  - https://hub.cosmos.network/main/hub-overview/
  - https://hub.cosmos.network/main/delegators/
- Sections and content is missing from the deployed docs, is this intentional:
  - Litepapers in top dir 
  - Launch (these are blog posts)
  - Migration
- Gov Proposals: => handled in #1035
  - Update to lead with number? 
  - Add frontmatter information
  - maybe link to where voted on is helpful?
- DOCS_BUILD out of date
  - Current small PR to update  :white_check_mark: 
  - Needs more info on aspects of docs like
    - Multilanguage support
    - Reccomended defaults for structure e.g., Cosmos theme reference YAML frontmatter:
      ```
      ---
      # title is displayed in the sidebar
      title: Title of the file
      # order specifies file's priority in the sidebar
      order: 2
      # parent is readme.md or index.md parent directory
      parent:
        title: Directory title
        order: 1
      ---
      ```
