### ISSUE TITLE
delegation and redelegation amount bug

### ISSUE THREAD

**Issue by yaruwangway** [cosmos/gaia#1229]
## Summary of Bug

Scenario Set Up:
1. Have at least 2 validators running. Lets call them val1 and val2
2. Delegate some amounts to both the validators. Does not matter how much and from which delegators.
3. Get val1 slashed and jailed. This will slash the whole staking amount of the validator as well as the related delegators
4. unjail the validator val1 and make sure it is running and in the bonded state.

So far so good. Everything is running as expected. Both val1's self-delegation amount as well as the amount from its delegators got slashed. No problem so far.
Now we move into the weird stuff.

Test
1. Delegate 10,000,000 tokens to val1 from an account (lets call it del1) that has never delegated to val1 before (Please make sure that this delegator DID NOT get slashed when val1 was slashed and jailed)
2. Since val1 had been jailed in the past, the delegation shares of del1 will not be equal to the number of tokens that had been delegated. More specifically, the delegations shares will be slightly higher than the number of tokens delegated.
3. The amount should show 9,999,999 tokens instead of 10,000,000 tokens since this amount is calculated from the delegation shares and some decimal part is truncated in the calculations.
```
- balance:
    amount: "9999999"
    denom: usaage
  delegation:
    delegator_address: saage1yjx2l0j5yfjws0p8kaaqmsj94af0j5wwyr2csm
    shares: "10001000.098552908034468393"
    validator_address: saagevaloper19ef0rhsk5ew2ny8u4hn3craru365gnz2cnqnma
```
This in itself should raise eyebrows. But we have worse problems ahead of us.

4. Try to redelegate the entire amount from val1 to val2. Make sure that val2 was NEVER slashed. You will find that it is possible to redelegate 10,000,000 tokens here even though the amount only shows 9,999,999 tokens. (courtesy of the shares which determine the actual calculation)
5. After redelegation is successful, you will find that only 9,999,999 tokens have been redelegated to val2 and not 10,000,000 tokens. Since val2 was never slashed, its token amount is equal to the delegation shares for every delegation. You should see something as follows:
delegation_responses:
```
- balance:
    amount: "9999999"
    denom: usaage
  delegation:
    delegator_address: saage1yjx2l0j5yfjws0p8kaaqmsj94af0j5wwyr2csm
    shares: "9999999.000000000000000000"
    validator_address: saagevaloper1dpjwfv8e03xnj4tqmvv0zkcltu5dx7kq39mfu4
```

1 token just got lost in the calculations.

Finally, if you are unlucky enough with the shares_per_token value, an even weirder scenario may arise. 
It had occurred in my tests a few times but not occurring now, so i cannot put in proof of my finding here.

After the complete redelegation to val2 , shares of val1 do not go down to zero although the amount does. Here is the result of a query from one time this happened:
```
- balance:
    amount: "0"
    denom: usaage
  delegation:
    delegator_address: saage19ef0rhsk5ew2ny8u4hn3craru365gnz2j2zeg2
    shares: "0.804521213320971357"
    validator_address: saagevaloper1j98uhhwzgl7tltpcp0jz4m0jh9ttxgsmmrsnkt
```

Do you wish me to update the github issue with this?

P.S: I am not using gaia (as you can see from the account addresses). I am using an app we are building with cosmos-sdk. But we did not modify any code in any of its modules 

## Steps to Reproduce

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
