### ISSUE TITLE
Starport support

### ISSUE THREAD

**Issue by fedekunze** [cosmos/gaia#519]
It'd be nice to have Starport support for gaia by adding the config file and UI so that users running local testnets can interact with the Hub easily. This could also mean for future testnets to be deployed using the `starport network` command.

@nylira @alessio @fadeev 

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by fadeev** [comment]
I like this idea 🙂 to which branch should I make a draft PR?

It essentially only needs a `config.yml`:

```yaml
version: 1
accounts:
  - name: alice
    coins: ["1000token", "100000000stake"]
  - name: bob
    coins: ["500token"]
validator:
  name: alice
  staked: "100000000stake"
```
