### ISSUE TITLE
Docker Github Action

### ISSUE THREAD

**Issue by faddat** [cosmos/gaia#726]
## Summary of Bug

https://github.com/cosmos/gaia/blob/main/.github/workflows/docker.yml

Also saw a "wrong password" error in a build job.  

Docker image uses Alpine, which makes great multiplatform builds, so we should specify that in the action and get those, as well. 

Looks like it is actually pushing to:

https://hub.docker.com/r/tendermint/gaia/tags?page=1&ordering=last_updated

## Version

dc11e61d815bf294a79c558e7b4a04d804d8daff

## Steps to Reproduce

Try to find where the Docker Github action pushes to.  

## Proposed Solution

Approximately:

```yaml
name: Publish Docker image
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  push_to_registry:
    name: Push Multiplatform Gaia Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
         run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Login to Packages Registry
        uses: docker/login-action@v1 
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          registry: docker.pkg.github.com
          repository: ${{ github.actor }}/gaia/gaia
          tags: ${{ GITHUB_REPOSITORY }}:${GITHUB_REF##*/},${{ GITHUB_REPOSITORY }}:${GITHUB_REF},
```

This provides:

* Something that can be forked into other repositories and still build
* Docker images by branch and commit hash

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
